import { AppShell } from '@/app/components/app-shell';
import { ReceiveMaterialForm } from '@/app/components/receive-material-form';
import { listJobs, listMaterials, listPurchaseOrderAlerts, listReceivingRecords } from '@/app/actions';
import { getRole } from '@/lib/role';

const errorMessages: Record<string, string> = {
  'missing-required-fields': 'Material, quantity, destination, invoice number, and vendor are required.',
  'job-required-for-job-destination': 'Please select a destination job when destination is Job.',
  'invalid-material': 'Selected material was not found.',
  'invalid-job': 'Destination job is invalid or closed.',
  'save-failed': 'Unable to save receipt right now. Please try again.'
};

export default async function ReceiveMaterialsPage({
  searchParams
}: {
  searchParams: { role?: string; error?: string; message?: string; success?: string };
}) {
  const role = getRole(searchParams.role);
  const [{ data: materials }, { data: jobs }, { data: receipts }, { data: poAlerts }] = await Promise.all([
    listMaterials(),
    listJobs(),
    listReceivingRecords(),
    listPurchaseOrderAlerts(5)
  ]);
  const openJobs = jobs.filter((job) => job.status === 'OPEN');
  const detailedMessage = searchParams.message ? decodeURIComponent(searchParams.message) : null;
  const errorMessage = detailedMessage || (searchParams.error ? errorMessages[searchParams.error] ?? 'Unable to receive material.' : null);
  const showSuccess = searchParams.success === '1';

  return (
    <AppShell role={role}>
      <section className="card">
        <div className="section-title">
          <h3>Receive Materials</h3>
          <p className="muted">Capture vendor receipts with invoice, destination, and optional photo reference.</p>
        </div>
        {errorMessage ? <p style={{ color: '#b42318', marginBottom: '0.75rem' }}>{errorMessage}</p> : null}
        {showSuccess ? <p style={{ color: '#027a48', marginBottom: '0.75rem' }}>Receipt posted successfully.</p> : null}
        <ReceiveMaterialForm materials={materials} jobs={openJobs} />
      </section>

      <section className="card">
        <div className="section-title">
          <h3>Recent PO Alerts</h3>
          <p className="muted">Visible notifications generated by matching RECEIVE invoice/PO numbers.</p>
        </div>
        {poAlerts.length === 0 ? (
          <p className="muted">No PO alerts yet.</p>
        ) : (
          <table>
            <thead>
              <tr>
                <th>Alerted</th>
                <th>PO</th>
                <th>Material</th>
                <th>Related Job</th>
                <th>Message</th>
              </tr>
            </thead>
            <tbody>
              {poAlerts.map((alert) => (
                <tr key={alert.id}>
                  <td>{new Date(alert.createdAt).toLocaleString()}</td>
                  <td>{alert.poNumber}</td>
                  <td>{alert.materialName}</td>
                  <td>{alert.relatedJobLabel}</td>
                  <td>{alert.message}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      <section className="card">
        <div className="section-title">
          <h3>Recent Receipts</h3>
          <p className="muted">Latest database-backed receive transactions.</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>Received</th>
              <th>Invoice #</th>
              <th>SKU</th>
              <th>Material</th>
              <th>Qty</th>
              <th>Destination</th>
              <th>Vendor</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {receipts.map((receipt) => (
              <tr key={receipt.id}>
                <td>{new Date(receipt.receivedAt).toLocaleString()}</td>
                <td>{receipt.invoiceNumber}</td>
                <td>{receipt.materialSku}</td>
                <td>{receipt.materialName}</td>
                <td>{receipt.quantity}</td>
                <td>{receipt.destinationLabel}</td>
                <td>{receipt.vendorName}</td>
                <td>{receipt.notes}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </AppShell>
  );
}
